//! Live ECAPA tests: require the ONNX model + the `onnx` feature, so they are
//! `#[ignore]`d (the default `cargo test` run needs no weights). Run with:
//!
//! ```text
//! cargo test -p clawft-voice-onnx --features onnx -- --ignored --nocapture
//! ```
//!
//! Fixtures (`tests/fixtures/*.wav`) are 16 kHz mono int16 clips; the parity
//! reference (`onyx_a_embedding.json`) is the `speechbrain/spkrec-ecapa-voxceleb`
//! embedding of `onyx_a.wav`, generated by the export tooling.

#![cfg(feature = "onnx")]

use std::path::PathBuf;

use clawft_channels::voice::speaker::SpeakerEmbedder;
use clawft_voice_onnx::EcapaEmbedder;

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn model_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../.weftos/models/ecapa/ecapa_tdnn.onnx")
}

fn read_wav_i16(name: &str) -> Vec<i16> {
    let path = fixtures().join(name);
    let mut reader =
        hound::WavReader::open(&path).unwrap_or_else(|e| panic!("open {}: {e}", path.display()));
    assert_eq!(reader.spec().sample_rate, 16_000, "fixture must be 16 kHz");
    reader.samples::<i16>().map(|s| s.unwrap()).collect()
}

fn read_ref_embedding() -> Vec<f32> {
    let bytes = std::fs::read(fixtures().join("onyx_a_embedding.json")).unwrap();
    serde_json::from_slice(&bytes).unwrap()
}

fn cosine(a: &[f32], b: &[f32]) -> f32 {
    let dot: f32 = a.iter().zip(b).map(|(x, y)| x * y).sum();
    let na: f32 = a.iter().map(|x| x * x).sum::<f32>().sqrt();
    let nb: f32 = b.iter().map(|x| x * x).sum::<f32>().sqrt();
    if na == 0.0 || nb == 0.0 {
        0.0
    } else {
        dot / (na * nb)
    }
}

#[tokio::test]
#[ignore = "requires ECAPA ONNX model under .weftos/models/ecapa/"]
async fn parity_against_speechbrain() {
    let emb = EcapaEmbedder::with_model(model_path());
    assert!(emb.is_runtime_available(), "model failed to load");

    let pcm = read_wav_i16("onyx_a.wav");
    let mine = emb.embed(&pcm, 16_000).await.unwrap();
    assert_eq!(mine.len(), 192);

    let reference = read_ref_embedding();
    let cos = cosine(&mine, &reference);
    println!("ECAPA parity cosine vs SpeechBrain reference: {cos:.6}");
    assert!(
        cos >= 0.99,
        "Rust ECAPA must match the SpeechBrain reference (cosine {cos:.6} < 0.99)"
    );
}

#[tokio::test]
#[ignore = "requires ECAPA ONNX model under .weftos/models/ecapa/"]
async fn same_speaker_beats_different() {
    let emb = EcapaEmbedder::with_model(model_path());
    assert!(emb.is_runtime_available(), "model failed to load");

    let onyx_a = emb
        .embed(&read_wav_i16("onyx_a.wav"), 16_000)
        .await
        .unwrap();
    let onyx_b = emb
        .embed(&read_wav_i16("onyx_b.wav"), 16_000)
        .await
        .unwrap();
    let dan = emb.embed(&read_wav_i16("dan.wav"), 16_000).await.unwrap();

    let same = cosine(&onyx_a, &onyx_b);
    let diff = cosine(&onyx_a, &dan);
    println!("same-speaker cosine {same:.4}  different-speaker cosine {diff:.4}");

    assert!(
        same > diff,
        "same-speaker ({same:.4}) must exceed different-speaker ({diff:.4})"
    );
    // The David profile's acceptance floor (ADR-061): same clears it, different
    // is rejected.
    assert!(
        same > 0.45,
        "same-speaker {same:.4} should clear the 0.45 floor"
    );
    assert!(
        diff < 0.45,
        "different-speaker {diff:.4} should fall below 0.45"
    );
}
