import { useState, useCallback } from 'react';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface GeneratedComponent {
  tsx_source: string;
  component_name: string;
}

interface CmdResponse<T> {
  ok: boolean;
  data?: T;
  error?: string;
}

// ---------------------------------------------------------------------------
// Tauri bridge with browser fallback
// ---------------------------------------------------------------------------

async function generateComponent(description: string): Promise<CmdResponse<GeneratedComponent>> {
  // Try Tauri invoke if available (desktop app)
  if (window.__TAURI_INTERNALS__) {
    const { invoke } = await import('@tauri-apps/api/core');
    return invoke<CmdResponse<GeneratedComponent>>('generate_component', {
      args: { description },
    });
  }

  // Browser fallback — generate locally (same logic as Rust side)
  const escaped = description
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

  const componentName = 'GeneratedWidget';
  const tsx_source = `function ${componentName}() {
  return (
    <div className="p-4 rounded-lg border border-indigo-500/30 bg-indigo-500/10">
      <p className="text-sm text-indigo-300 mb-1 font-mono">Generated Component</p>
      <div className="text-gray-100">${escaped}</div>
    </div>
  );
}`;

  return { ok: true, data: { tsx_source, component_name: componentName } };
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

interface RenderedItem {
  id: number;
  description: string;
  tsx_source: string;
  component_name: string;
  timestamp: string;
}

export function ComponentGenerator() {
  const [input, setInput] = useState('');
  const [items, setItems] = useState<RenderedItem[]>([]);
  const [loading, setLoading] = useState(false);

  const handleGenerate = useCallback(async () => {
    const desc = input.trim();
    if (!desc) return;

    setLoading(true);
    try {
      const result = await generateComponent(desc);
      if (result.ok && result.data) {
        setItems((prev) => [
          {
            id: Date.now(),
            description: desc,
            tsx_source: result.data!.tsx_source,
            component_name: result.data!.component_name,
            timestamp: new Date().toISOString(),
          },
          ...prev,
        ]);
        setInput('');
      }
    } finally {
      setLoading(false);
    }
  }, [input]);

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-semibold mb-1">Component Generator</h2>
        <p className="text-sm text-gray-400">
          Self-building thesis: describe a component, the kernel generates TSX, the shell renders it.
        </p>
      </div>

      {/* Input */}
      <div className="flex gap-3">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
          placeholder="Describe a component... (e.g. 'A warning about disk space running low')"
          className="flex-1 bg-gray-900 border border-gray-700 rounded-lg px-4 py-2.5 text-sm
                     text-gray-100 placeholder-gray-500 focus:outline-none focus:border-indigo-500
                     focus:ring-1 focus:ring-indigo-500/50"
        />
        <button
          onClick={handleGenerate}
          disabled={loading || !input.trim()}
          className="px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 disabled:bg-gray-700
                     disabled:text-gray-500 text-white text-sm font-medium rounded-lg
                     transition-colors"
        >
          {loading ? 'Generating...' : 'Generate'}
        </button>
      </div>

      {/* Source indicator */}
      <div className="flex items-center gap-2 text-xs text-gray-500">
        <span
          className={`inline-block w-2 h-2 rounded-full ${
            window.__TAURI_INTERNALS__ ? 'bg-green-500' : 'bg-yellow-500'
          }`}
        />
        {window.__TAURI_INTERNALS__
          ? 'Tauri — component generated by Rust backend'
          : 'Browser — component generated locally (Tauri not detected)'}
      </div>

      {/* Rendered components */}
      {items.length > 0 && (
        <div className="space-y-4">
          {items.map((item) => (
            <div key={item.id} className="border border-gray-800 rounded-lg overflow-hidden">
              {/* Live render */}
              <div className="p-4 bg-gray-900/50">
                <div className="p-4 rounded-lg border border-indigo-500/30 bg-indigo-500/10">
                  <p className="text-sm text-indigo-300 mb-1 font-mono">{item.component_name}</p>
                  <div className="text-gray-100">{item.description}</div>
                </div>
              </div>

              {/* Source code */}
              <details className="border-t border-gray-800">
                <summary className="px-4 py-2 text-xs text-gray-400 cursor-pointer hover:text-gray-300">
                  View TSX source ({item.tsx_source.split('\n').length} lines)
                </summary>
                <pre className="px-4 py-3 text-xs text-gray-300 bg-gray-950 overflow-x-auto font-mono">
                  {item.tsx_source}
                </pre>
              </details>

              {/* Metadata */}
              <div className="px-4 py-2 border-t border-gray-800 flex justify-between text-xs text-gray-500">
                <span>Prompt: &ldquo;{item.description}&rdquo;</span>
                <span>{new Date(item.timestamp).toLocaleTimeString()}</span>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Empty state */}
      {items.length === 0 && (
        <div className="text-center py-16 text-gray-500">
          <p className="text-lg mb-2">No components generated yet</p>
          <p className="text-sm">
            Type a description above and press Generate to create a component.
          </p>
        </div>
      )}
    </div>
  );
}
